### ISSUE TITLE
Create starter-kit: instructions for starting a new WiMLDS chapter

### ISSUE THREAD

**Issue by ledell** [WiMLDS/starter-kit#1]
Use the R-Ladies Starter kit as a template: https://github.com/rladies/starter-kit

**Comment by margaretpearce** [comment]
Getting closer! Some things on the R-Ladies starter kit I'm not sure we have an equivalent of for WiMLDS. For example, the R-Ladies starter kit has a page on getting email addresses - do we have anything like that? (https://github.com/rladies/starter-kit/wiki/How-to-access-your-rladies-email-address)

**Comment by ledell** [comment]
@margaretpearce We do have that option to have a wimlds.org email, so you could add a section for that, or even easier, just point to the R-Ladies one (rladies and wimlds use the same hosting company, just a different domain, so the instructions are transferrable).

**Comment by margaretpearce** [comment]
Great, thanks @ledell! I added a copy of the rladies page and updated the URLs to refer to WiMLDS.org. I think we are all set for now. Let me know if there's anything else missing!

**Comment by ledell** [comment]
@margaretpearce This is fantastic!  Thank you for doing this.

**Comment by sinzianaeckner** [comment]
This is awesome!
